# Generated by Django 4.1.7 on 2023-10-24 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='status',
        ),
    ]
