# Generated by Django 4.1.7 on 2023-11-07 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_paid_through_purchasepayment_bank_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary_duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.TextField(max_length=30)),
                ('term_value', models.IntegerField()),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee')),
            ],
        ),
    ]
