# Generated by Django 4.1.7 on 2023-10-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_payrollemployee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollemployee',
            name='status',
        ),
    ]
