# Generated by Django 4.1.7 on 2023-10-31 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_payrollemployee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='paymentmethod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.paymentmethod'),
        ),
    ]
