# Generated by Django 4.1.7 on 2023-11-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_deletedpurchasepayments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
