# Generated by Django 4.1.7 on 2023-10-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_purchasepayment_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='paymentmethod',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
