# Generated by Django 4.1.7 on 2023-11-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_purchasepayment_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='pymntid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
