# Generated by Django 4.1.7 on 2023-10-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_payrollemployee_acno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='acno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='adharnumber',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='bankdetails',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='bankname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='bloodgroup',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='branchname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='dateofbirth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='effectivefrom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='employeeno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='employees',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='esinumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='fathersmothersname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='file',
            field=models.FileField(default='', upload_to='payrollemployee'),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='function',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='generalphone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='hours',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='ifsccode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='istds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='joindate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='pannumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='payhead',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='pfaccountnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='pincode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='praccountnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='rate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='salarydetails',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='spousename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tdstype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tempcity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tempcountry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='temppincode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tempstate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='tempstreet',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='transactiontype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payrollemployee',
            name='universalaccountnumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
