# Generated by Django 4.1.7 on 2023-11-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_purchasepayment_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='reference',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='purchasepayment',
            table=None,
        ),
        migrations.DeleteModel(
            name='LastReference',
        ),
    ]
