# Generated by Django 4.1.7 on 2023-10-16 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_payrollemployee_status_payrollemployee_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='paid_through',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='upi_id',
        ),
    ]
