# Generated by Django 4.1.7 on 2023-11-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_purchasebill_amtrecvd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='balance_due',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='cgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='contact_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='credit_period',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='customer_gstin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='customer_gsttype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='deliver_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='deliverto',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='destiofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='discount',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='due_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='file',
            field=models.FileField(default='default.png', upload_to='purchase/bill'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='grand_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='igst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='is_from_purchase_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='round_off',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='sgst',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='ship_charge',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='sourceofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='sub_total',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tax_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tcs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='tcs_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='total_discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='upi_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='vendor_balance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='vendor_gstin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='vendor_gsttype',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed'), ('Save', 'Save')], default='Draft', max_length=150),
        ),
    ]
