# Generated by Django 4.1.7 on 2023-10-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_purchasepayment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='status',
            field=models.CharField(default='Active', max_length=100),
        ),
    ]
