# Generated by Django 4.1.7 on 2023-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_purchasebill_account_number_purchasebill_amtrecvd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasebill',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='customer_gstin',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='customer_gsttype',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='is_from_purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='upi_number',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='vendor_balance',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='vendor_gstin',
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='vendor_gsttype',
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Billed', 'Billed')], default='Billed', max_length=150),
        ),
    ]
