# Generated by Django 4.1.7 on 2023-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_remove_payrollemployee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollemployee',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='bank_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='cheque_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='paid_through',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
