# Generated by Django 4.1.7 on 2023-10-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_payrollemployee_is_active_purchasepayment_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasepayment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='cheque_number',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='paid_through',
        ),
        migrations.RemoveField(
            model_name='purchasepayment',
            name='upi_id',
        ),
    ]
