# Generated by Django 4.1.7 on 2023-12-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_payrollemployee_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastReferenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reference', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchasebill',
            name='balance_due',
        ),
    ]
