# Generated by Django 4.1.7 on 2023-10-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_purchasepayment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='account_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='cash',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='cheque_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='paid_through',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment',
            name='upi_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
