# Generated by Django 4.1.7 on 2023-12-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_lastreferencenumber_remove_purchasebill_balance_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='balance_due',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
