# Generated by Django 4.1.7 on 2023-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_purchasepayment_email_purchasepayment_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='status',
            field=models.CharField(default='Draft', max_length=100),
        ),
    ]
