# Generated by Django 4.1.7 on 2023-12-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_deletedpurchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment1',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasepayment1',
            name='payment_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DeletedPurchasePayment',
        ),
    ]
