# Generated by Django 4.1.7 on 2023-12-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_purchasepayment1_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payment_id',
            field=models.IntegerField(null=True),
        ),
    ]
