# Generated by Django 4.1.7 on 2023-12-13 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_purchasepayment1_payment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_reference', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
        migrations.DeleteModel(
            name='LastReferenceNumber',
        ),
    ]
