# Generated by Django 4.1.7 on 2023-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_convertbill_deletedchallan_deletedcreditnotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payments',
            field=models.TextField(null=True),
        ),
    ]
