# Generated by Django 4.1.7 on 2023-12-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_purchasepayment1_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment1',
            name='pymnt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasepayment'),
            preserve_default=False,
        ),
    ]
