# Generated by Django 4.1.7 on 2023-12-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_alter_purchasepayment1_payments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='pymnt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.purchasepayment'),
        ),
    ]
