# Generated by Django 4.1.7 on 2023-12-26 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_purchasepayment1_pymnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='converted_inv',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='converted_rec',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='challanitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.itemtable'),
        ),
        migrations.AddField(
            model_name='customer',
            name='pay_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_list',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='cheque_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='purchasedebit',
            name='upi_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='debit_no',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
