# Generated by Django 4.1.7 on 2024-01-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_deletedpaymentmade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='amountdue',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payments',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
