# Generated by Django 4.1.7 on 2024-01-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_alter_purchasepayment1_amountdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='amtcredit',
            field=models.FloatField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='amtreceived',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='paymentamount',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
