# Generated by Django 4.1.7 on 2024-01-22 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_alter_vendor_opblnc_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDetails1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('casual_leave', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leave', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('working_days', models.IntegerField(default=0)),
                ('holiday', models.IntegerField(default=0)),
                ('other_cuttings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('add_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(default='Draft', max_length=20)),
                ('leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='employeeid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.payrollemployee'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='bankaccountholder',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='bankconfiguration',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='bankingdetails',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='adjust',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='convert_invoice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='convert_reinvoice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='convert_salesorder',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_inv',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_invoice_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_rec',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_recurring_invoice_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_sales',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='converted_sales_order_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='is_converted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='term_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='bank_acc_number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='paid_bank_acc_number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='paid_cheque',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='paid_upi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='recieved_cheque',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_account',
            name='recieved_upi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='bank_acc_number',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='recieved_cheque',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan_transaction',
            name='recieved_upi',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailingaddress',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='Open_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='openingbalance',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.company'),
        ),
        migrations.AddField(
            model_name='purchasebill',
            name='csourceofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='csourceofsupply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='balance_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccountholder',
            name='account_type',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('BA', 'Bank Account')], default='BA', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankingdetails',
            name='registration_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('composition', 'Composition'), ('consumer', 'Consumer'), ('unregistered', 'Unregistered')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.customer'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent')], default='Draft', max_length=150),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='mailingaddress',
            name='state',
            field=models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chhattisgarh'), ('DL', 'National Capital Territory of Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('LA', 'Ladakh'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UT', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('WB', 'West Bengal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='balance_due',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='amtrecvd',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='balance_amount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='debit_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='paid_amount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='grand_total',
            field=models.FloatField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DeletedPaymentMade',
        ),
    ]
