# Generated by Django 4.1.7 on 2024-01-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_salarydetails1_attendance_employeeid_bankaccount_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='amtrecvd',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
