# Generated by Django 4.1.7 on 2024-01-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_purchasebill_amtrecvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment1',
            name='payments',
            field=models.FloatField(null=True),
        ),
    ]
